"""PR Pipeline - Create separate PRs per CODEOWNERS group."""

import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from collections import defaultdict

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn

from clean_docs.cache import CacheManager
from clean_docs.codeowners import CodeOwners
from clean_docs.config import Config
from clean_docs.fixer import Fix, LinkFixer
from clean_docs.link_checker import CheckResults, LinkChecker, LinkResult, LinkStatus
from clean_docs.parsers.markdown import MarkdownParser, MarkdownDocument


@dataclass
class OwnerGroup:
    """A group of files owned by the same team."""

    owner_key: str
    owners: List[str]
    files: List[Path]
    broken_links: List[Tuple[Path, LinkResult]]
    fixes: List[Fix] = field(default_factory=list)

    @property
    def auto_fixable_count(self) -> int:
        return sum(1 for f in self.fixes if f.auto_fixable)

    @property
    def broken_count(self) -> int:
        return len(self.broken_links)

    def get_branch_name(self) -> str:
        """Generate a safe git branch name for this owner group."""
        # Use first owner, sanitized for git branch name
        if not self.owners:
            return "clean-docs/fix-no-owner"

        owner = self.owners[0]
        # Remove @ and special chars, replace / with -
        safe_name = owner.lstrip("@").replace("/", "-").replace("_", "-")
        safe_name = re.sub(r"[^a-zA-Z0-9-]", "", safe_name)
        return f"clean-docs/fix-{safe_name}"

    def get_pr_title(self) -> str:
        """Generate PR title for this owner group."""
        return (
            f"fix(docs): Fix {self.auto_fixable_count} broken links in {self.owners[0]} owned files"
        )

    def get_pr_body(self, base_path: "Optional[Path]" = None) -> str:
        """Generate PR body with details of fixes.

        Args:
            base_path: Base path for computing relative paths. If provided,
                       file paths will be shown as relative to this path.
        """

        def relative_path(p: Path) -> str:
            if base_path:
                try:
                    return str(p.relative_to(base_path))
                except ValueError:
                    pass
            return str(p)

        lines = []
        lines.append("## Summary")
        lines.append("")
        lines.append(
            f"This PR fixes **{self.auto_fixable_count}** broken documentation links in files owned by {', '.join(self.owners)}."
        )
        lines.append("")
        lines.append("## Changes")
        lines.append("")

        # Group fixes by file
        fixes_by_file: Dict[Path, List[Fix]] = defaultdict(list)
        for fix in self.fixes:
            if fix.auto_fixable:
                fixes_by_file[fix.file_path].append(fix)

        for file_path, file_fixes in sorted(fixes_by_file.items()):
            lines.append(f"### `{relative_path(file_path)}`")
            lines.append("")
            lines.append("| Line | Change | Description |")
            lines.append("|------|--------|-------------|")
            for fix in file_fixes:
                change = f"`{fix.original_url}` → `{fix.suggested_url}`"
                lines.append(f"| {fix.line} | {change} | {fix.description} |")
            lines.append("")

        # Add remaining broken links that couldn't be auto-fixed
        manual_count = self.broken_count - self.auto_fixable_count
        if manual_count > 0:
            lines.append("## Remaining Issues")
            lines.append("")
            lines.append(f"**{manual_count}** broken links require manual review:")
            lines.append("")

            fixed_urls = {f.original_url for f in self.fixes if f.auto_fixable}
            for file_path, link_result in self.broken_links:
                if link_result.link.url not in fixed_urls:
                    lines.append(
                        f"- `{relative_path(file_path)}` line {link_result.link.line}: `{link_result.link.url}`"
                    )
            lines.append("")

        lines.append("---")
        lines.append("*Generated by [clean-docs](https://github.com/Algiras/clean-docs)*")

        return "\n".join(lines)


class PRPipeline:
    """Pipeline to create PRs grouped by CODEOWNERS."""

    def __init__(
        self,
        base_path: Path,
        console: Console,
        config: Config,
        codeowners: CodeOwners,
    ):
        self.base_path = base_path
        self.console = console
        self.config = config
        self.codeowners = codeowners
        self.parser = MarkdownParser()
        self.owner_groups: Dict[str, OwnerGroup] = {}

    async def run(
        self,
        markdown_files: List[Path],
        cache: CacheManager,
        ignore_patterns: List[str],
        dry_run: bool = False,
        create_prs: bool = True,
        base_branch: str = "main",
        skip_owners: Optional[List[str]] = None,
        only_owners: Optional[List[str]] = None,
    ) -> Dict[str, dict]:
        """Run the full PR pipeline.

        Returns a dict of owner_key -> result info
        """
        skip_owners = skip_owners or []
        results = {}

        # Step 1: Scan and group by owner
        self.console.print(
            Panel.fit(
                "[bold blue]PR Pipeline[/bold blue]\n"
                f"Files: {len(markdown_files)}\n"
                f"Base branch: {base_branch}",
                border_style="blue",
            )
        )

        self.console.print("\n[bold]Step 1:[/bold] Scanning for broken links...")
        await self._scan_and_group(markdown_files, cache, ignore_patterns)

        if not self.owner_groups:
            self.console.print("[green]No broken links found![/green]")
            return results

        # Show summary
        self._print_owner_summary()

        # Filter owner groups
        groups_to_process = []
        for owner_key, group in self.owner_groups.items():
            if only_owners and not any(o in owner_key for o in only_owners):
                continue
            if any(o in owner_key for o in skip_owners):
                continue
            if group.auto_fixable_count == 0:
                continue
            groups_to_process.append(group)

        if not groups_to_process:
            self.console.print("[yellow]No auto-fixable issues in selected owner groups.[/yellow]")
            return results

        self.console.print(
            f"\n[bold]Step 2:[/bold] Processing {len(groups_to_process)} owner groups with auto-fixable issues..."
        )

        # Step 2: Process each owner group
        for group in groups_to_process:
            self.console.print(f"\n[cyan]━━━ Processing: {', '.join(group.owners)} ━━━[/cyan]")

            result = await self._process_owner_group(
                group,
                cache,
                ignore_patterns,
                dry_run=dry_run,
                create_pr=create_prs,
                base_branch=base_branch,
            )
            results[group.owner_key] = result

        # Final summary
        self._print_final_summary(results)

        return results

    async def _scan_and_group(
        self,
        markdown_files: List[Path],
        cache: CacheManager,
        ignore_patterns: List[str],
    ):
        """Scan files and group broken links by owner."""
        # Parse all documents
        documents = []
        for file_path in markdown_files:
            try:
                doc = self.parser.parse_file(file_path)
                if doc.links:
                    documents.append(doc)
            except Exception:
                pass

        if not documents:
            return

        # Check all links
        async with LinkChecker(
            cache=cache,
            timeout=self.config.links.timeout,
            concurrency=self.config.links.concurrency,
            ignore_patterns=ignore_patterns,
        ) as checker:
            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                console=self.console,
                transient=True,
            ) as progress:
                task = progress.add_task("Checking links...", total=len(documents))

                for doc in documents:
                    result = await checker.check_document(doc, self.base_path)
                    self._add_to_owner_groups(doc, result)
                    progress.update(task, advance=1)

        # Analyze fixes for each group
        fixer = LinkFixer(self.base_path, self.console, self.config)
        for group in self.owner_groups.values():
            for file_path, link_result in group.broken_links:
                doc = self.parser.parse_file(file_path)
                fix = fixer._analyze_broken_link(doc, link_result)
                if fix:
                    group.fixes.append(fix)

    def _add_to_owner_groups(self, doc: MarkdownDocument, check_result: CheckResults):
        """Add broken links to appropriate owner groups."""
        try:
            rel_path = str(doc.path.relative_to(self.base_path))
        except ValueError:
            rel_path = str(doc.path)

        owner_key = self.codeowners.get_owner_key(rel_path)
        owners = self.codeowners.get_owners(rel_path)

        if owner_key not in self.owner_groups:
            self.owner_groups[owner_key] = OwnerGroup(
                owner_key=owner_key,
                owners=owners,
                files=[],
                broken_links=[],
            )

        group = self.owner_groups[owner_key]

        # Track files with broken links
        has_broken = False
        for result in check_result.results:
            if result.status == LinkStatus.BROKEN:
                group.broken_links.append((doc.path, result))
                has_broken = True

        if has_broken and doc.path not in group.files:
            group.files.append(doc.path)

    def _print_owner_summary(self):
        """Print summary of broken links by owner."""
        table = Table(show_header=True, header_style="bold magenta")
        table.add_column("Owner", style="cyan")
        table.add_column("Broken", justify="right")
        table.add_column("Auto-fixable", justify="right")
        table.add_column("Files", justify="right")

        total_broken = 0
        total_fixable = 0

        for owner_key in sorted(self.owner_groups.keys()):
            group = self.owner_groups[owner_key]
            total_broken += group.broken_count
            total_fixable += group.auto_fixable_count

            owner_display = ", ".join(group.owners) if group.owners else "(no owner)"
            fixable_str = (
                f"[green]{group.auto_fixable_count}[/green]" if group.auto_fixable_count else "0"
            )

            table.add_row(
                owner_display,
                str(group.broken_count),
                fixable_str,
                str(len(group.files)),
            )

        self.console.print("\n[bold]Broken Links by Owner:[/bold]")
        self.console.print(table)
        self.console.print(
            f"\n[dim]Total: {total_broken} broken, {total_fixable} auto-fixable[/dim]"
        )

    async def _process_owner_group(
        self,
        group: OwnerGroup,
        cache: CacheManager,
        ignore_patterns: List[str],
        dry_run: bool,
        create_pr: bool,
        base_branch: str,
    ) -> dict:
        """Process a single owner group - apply fixes and optionally create PR."""
        result = {
            "owner_key": group.owner_key,
            "owners": group.owners,
            "broken_count": group.broken_count,
            "auto_fixable_count": group.auto_fixable_count,
            "fixes_applied": 0,
            "branch": None,
            "pr_url": None,
            "error": None,
        }

        if group.auto_fixable_count == 0:
            self.console.print("[yellow]  No auto-fixable issues[/yellow]")
            return result

        branch_name = group.get_branch_name()
        result["branch"] = branch_name

        if dry_run:
            self.console.print(f"  [dim]Would create branch:[/dim] {branch_name}")
            self.console.print(f"  [dim]Would fix:[/dim] {group.auto_fixable_count} links")
            self._print_proposed_fixes(group)
            return result

        try:
            # Create branch from base
            self.console.print(f"  Creating branch: {branch_name}")
            self._run_git(["checkout", base_branch])
            self._run_git(["pull", "origin", base_branch])

            # Delete branch if it exists
            try:
                self._run_git(["branch", "-D", branch_name])
            except subprocess.CalledProcessError:
                pass  # Branch didn't exist

            self._run_git(["checkout", "-b", branch_name])

            # Apply fixes
            fixer = LinkFixer(self.base_path, self.console, self.config)
            fixer.fixes = group.fixes
            attempted, succeeded = fixer.apply_fixes(dry_run=False)
            result["fixes_applied"] = succeeded

            self.console.print(f"  [green]Applied {succeeded}/{attempted} fixes[/green]")

            if succeeded == 0:
                self.console.print("  [yellow]No fixes applied, skipping PR[/yellow]")
                self._run_git(["checkout", base_branch])
                return result

            # Commit changes
            self._run_git(["add", "-A"])
            commit_msg = f"fix(docs): Fix {succeeded} broken links\n\nAuto-fixed by clean-docs for {', '.join(group.owners)}"
            self._run_git(["commit", "-m", commit_msg])

            if create_pr:
                # Push and create PR
                self.console.print("  Pushing branch...")
                self._run_git(["push", "-u", "origin", branch_name, "--force"])

                self.console.print("  Creating PR...")
                pr_url = self._create_pr(group, base_branch)
                result["pr_url"] = pr_url
                self.console.print(f"  [green]PR created:[/green] {pr_url}")

            # Return to base branch
            self._run_git(["checkout", base_branch])

        except subprocess.CalledProcessError as e:
            result["error"] = f"Git error: {e}"
            self.console.print(f"  [red]Error:[/red] {e}")
            try:
                self._run_git(["checkout", base_branch])
            except subprocess.CalledProcessError:
                pass  # Ignore checkout failures during error recovery
        except Exception as e:
            result["error"] = str(e)
            self.console.print(f"  [red]Error:[/red] {e}")

        return result

    def _print_proposed_fixes(self, group: OwnerGroup):
        """Print proposed fixes for dry-run mode."""
        auto_fixes = [f for f in group.fixes if f.auto_fixable]
        if not auto_fixes:
            return

        table = Table(show_header=True, header_style="bold green", show_lines=False)
        table.add_column("File", style="cyan", max_width=40)
        table.add_column("Line", justify="right")
        table.add_column("Change", max_width=50)

        for fix in auto_fixes[:10]:  # Show first 10
            change = f"{fix.original_url} → {fix.suggested_url}"
            if len(change) > 50:
                change = change[:47] + "..."
            table.add_row(str(fix.file_path.name), str(fix.line), change)

        if len(auto_fixes) > 10:
            table.add_row("...", "", f"({len(auto_fixes) - 10} more)")

        self.console.print(table)

    def _run_git(self, args: List[str]) -> str:
        """Run a git command and return output."""
        result = subprocess.run(
            ["git"] + args,
            cwd=self.base_path,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()

    def _create_pr(self, group: OwnerGroup, base_branch: str) -> str:
        """Create a GitHub PR using gh CLI."""
        title = group.get_pr_title()
        body = group.get_pr_body(base_path=self.base_path)

        # Build reviewer list from owners
        reviewers = []
        for owner in group.owners:
            if owner.startswith("@"):
                # Could be user or team
                if "/" in owner:
                    # Team: @org/team-name
                    reviewers.append(owner.lstrip("@"))
                else:
                    # User: @username
                    reviewers.append(owner.lstrip("@"))

        cmd = [
            "gh",
            "pr",
            "create",
            "--title",
            title,
            "--body",
            body,
            "--base",
            base_branch,
        ]

        # Add reviewers if available
        if reviewers:
            # gh pr create uses --reviewer for users, --team-reviewer for teams (doesn't exist)
            # For teams, we'll mention them in the body instead
            user_reviewers = [r for r in reviewers if "/" not in r]
            if user_reviewers:
                cmd.extend(["--reviewer", ",".join(user_reviewers)])

        result = subprocess.run(
            cmd,
            cwd=self.base_path,
            capture_output=True,
            text=True,
            check=True,
        )

        # gh pr create outputs the PR URL
        return result.stdout.strip()

    def _print_final_summary(self, results: Dict[str, dict]):
        """Print final summary of all operations."""
        self.console.print("\n" + "=" * 60)
        self.console.print("[bold]Pipeline Summary[/bold]\n")

        table = Table(show_header=True, header_style="bold")
        table.add_column("Owner")
        table.add_column("Fixes Applied", justify="right")
        table.add_column("PR", style="cyan")
        table.add_column("Status")

        for owner_key, result in results.items():
            owner = ", ".join(result["owners"]) if result["owners"] else "(no owner)"
            fixes = str(result["fixes_applied"])
            pr = result["pr_url"] or "-"

            if result["error"]:
                status = f"[red]Error: {result['error'][:30]}[/red]"
            elif result["pr_url"]:
                status = "[green]PR Created[/green]"
            elif result["fixes_applied"] > 0:
                status = "[yellow]Fixed (no PR)[/yellow]"
            else:
                status = "[dim]No fixes[/dim]"

            table.add_row(owner[:30], fixes, pr[:50] if pr != "-" else pr, status)

        self.console.print(table)
